AllCops:
  NewCops: enable
  Exclude:
    - '**/node_modules/**/*'
    - 'bin/bundle'
    - 'spec/rails_helper.rb'
    - 'test/channels/application_cable/connection_test.rb'
    - 'test/test_helper.rb'
    - 'db/schema.rb'
    - 'config/environments/*'
    
Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/LineLength:
    IgnoredPatterns: ['(\A|\s)#']
